name = 'lackluster'
licenselink = 'https://github.com/jwarykowski/lackluster-hugo/LICENSE'
license = 'MIT'
description = 'lackluster theme inspired by lackluster.nvim'

homepage = 'https://github.com/jwarykowski/lackluster-hugo'
demosite = 'https://lackluster-hugo.pages.dev'

tags = ["minimal", "responsive", "lackluster"]
features = ["responsive", "SEO-friendly"]

[author]
  name = 'Jonathan Warykowski'
  homepage = 'https://jwarykowski.dev'
